name: "Issue report"
description: Report an unexpected problem or unintended behavior.
labels: ["needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        It looks like this is your first issue. Welcome! 👋
        One of the project maintainers will be with you as soon as possible. We
        appreciate your patience. To safeguard the health of the project, please
        take a moment to read our [code of conduct](../blob/main/CODE_OF_CONDUCT.md).
  - type: markdown
    attributes:
      value: >
        It looks like this is your first issue. Welcome! 👋
        One of the project maintainers will be with you as soon as possible. We
        appreciate your patience. To safeguard the health of the project, please
        take a moment to read our [code of conduct](../blob/main/CODE_OF_CONDUCT.md).
  - type: checkboxes
    id: checklist
    attributes:
      label: "Before submitting the issue, check you have done the following:"
      description: Make sure you have provided all the information below so we can help resolve your issue.
      options:
        - label: Issue can be reproduced on this repository following [quick-start instructions](https://github.com/mdn/django-locallibrary-tutorial#quick-start).
          required: true
        - label: I am using a clean/fresh database
          required: true
        - label: I have included output logs and information about my environment setup below.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: What was incorrect, unhelpful, or unexpected?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output logs
      description: |
        Share any logs that describe the problem you are seeing. If you are seeing an error, please include the full error message.
      placeholder: |
        You can paste the output directly or upload it as an attachment.
  - type: textarea
    id: more-info
    attributes:
      label: Do you have anything more you want to share?
      description: For example, steps to reproduce, screenshots, screen recordings, or sample code.
