name: "Issue report"
description: Report an unexpected problem or unintended behavior.
labels: ["needs triage"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Before posting an issue, please confirm
      description: You may select more than one.
      options:
        - label: Issue can be reproduced on this repository following [quick-start instructions](https://github.com/mdn/django-locallibrary-tutorial#quick-start).
          validations:
            required: true
        - label: I am using a clean/fresh database
          validations:
            required: true
        - label: I have included output logs and information about my environment setup below.
          validations:
            required: true
  - type: markdown
    attributes:
      value: |
        ### Before you start

        **Want to fix the problem yourself?** This project is open source and we welcome fixes and improvements from the community!

        ↩ Check the project [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) guide to see how to get started.

        ---
  - type: textarea
    id: problem
    attributes:
      label: What information was incorrect, unhelpful, or incomplete?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Do you have any supporting links, references, or citations?
      description: Link to information that helps us confirm your issue.
  - type: textarea
    id: more-info
    attributes:
      label: Do you have anything more you want to share?
      description: For example, steps to reproduce, screenshots, screen recordings, or sample code.
